### PR TITLE
SLF4J-related fixes

### PR DESCRIPTION
**Pull request by dtrebbien**

### CODE REVIEW

**Comment by mprimi** [comment]
@dtrebbien thanks for these fixes, they all look good, but can we maybe get all of them in a single PR? (we can still preserve the 4 commits, if we merge without squashing).

**Comment by dtrebbien** [comment]
Sure. I will cherry pick the other commits to this PR.

**Comment by dtrebbien** [comment]
Done

**Comment by tgianos** [comment]
Thanks for cleaning up some technical debt @dtrebbien!

**Pull request merged**
