### PR TITLE
#463 quoted user column

### PR DESCRIPTION
**Pull request by chandnisingh**

### CODE REVIEW

**Comment by tgianos** [comment]
Hello @chandnisingh I see you opened an issue against this. Clearly it breaks all the tests when the new annotation definition is defined the way you tried to change it. Are you attempting to generate your schema via JPA schema auto generation? Genie isn't set up to do this for Mysql or Postgres. We have schema definition files in the `genie-ddl` directory. Are you still having problems even when you run against that schema?

**Comment by tgianos** [comment]
Note you can find the Schema file for 3.0.0 [here](https://github.com/Netflix/genie/blob/v3.0.0/genie-ddl/src/main/sql/postgresql/3.0.0-schema.postgresql.sql)

**Comment by chandnisingh** [comment]
@tgianos I used the schema file for 3.0.0. 
It was giving the error which I posted. I was able to build the app jar locally with the change I made. After which I was able  to save configuration.

**Comment by tgianos** [comment]
Hi @chandnisingh I've confirmed that as it's currently written it doesn't work with Postgres due to the `user` column. We believed this worked when the schema was done but since we don't use Postgres internally the integration tests on travis work against MySQL. Unfortunately while your fix does work for Postgres and should be the JPA 2.0 standard it looks like it breaks the tests for HSQLDB and possibly MySQL. I think at this point it's more prudent to rename the column from the protected `user` keyword to something like `genie_user`. I'll work on this when I get a chance and push a patch 3.0.1 release with an upgrade script for schemas. For now it sounds like you have a binary compiled locally you can work with. Let us know if you're blocked otherwise. @ajoymajumdar FYI

**Pull request closed without merging**
