### PR TITLE
add prometheus metrics for Genie

### PR DESCRIPTION
**Pull request by sbock-slack**
- Add dependencies to Genie that are needed to support the `/admin/prometheus` endpoint.

- We've built our own JARs and are already using Prometheus to power our metrics around Genie's health. Hoping to remove the need for us to locally fork Genie by getting this into open source 👍

### CODE REVIEW

**Comment by bhou2** [comment]
Thanks @babourine-slack I did not get the notification about this PR in the past several weeks. Checking.

**Review by bhou2 — COMMENTED** [review]
Could you clarify the tests you have done?

**Comment by babourine-slack** [comment]
> Could you clarify the tests you have done?

We built it locally with all tests as well as running it in prod for weeks now w/o any issues.

**Comment by babourine-slack** [comment]
👋 Hi @bhou2 ! Hope all's well! Dont know if ^ fell thru for you in notifications as your message for me 🤦 (I had to set some :) ) Pls let me know if you need any additional context. Also, if it'll help, we can setup a meeting just to meet and greet the teams on both sides (zoom, goog meet, ....) -- let me know if that's something you'll be interested in.

**Comment by sbock-slack** [comment]
Hey @bhou2, nice to meet you. Freshly back from paternity leave, looks like @babourine-slack has already answered with all the details I have. Definitely echoing his comment, happy to hop on a meet/zoom if it would help build confidence in our changes 👍

**Review by babourine-slack — APPROVED** [review]

**Comment by bhou2** [comment]
Great meeting with your team. Looking forward to our continuous communications and collaborations. PR approved as you confirmed that this code change has been running and tested in production for a long time.

**Review by bhou2 — APPROVED** [review]

**Comment by babourine-slack** [comment]
Thanks @bhou2 ! It was great meeting you and the team! We're looking forward to working with you on the project!

**Pull request merged**
